services:
  nightly-website:
    build: 
      context: ./main
      dockerfile: ./platforms/website/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - "PORT=8002"
      - SERVER_ENV=production
      - VITE_NIGHTLY=true
    container_name: nightly-website
    restart: always

  production-website:
    build: 
      context: ./production
      dockerfile: ./platforms/website/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - "PORT=8001"
      - "SERVER_ENV=production"
    container_name: production-website
    restart: always