services:
  web:
    build: 
      context: .
    ports:
      - "8002:8002"
    environment:
      - "PORT=8002"
      - "SERVER_ENV=production"
    container_name: nightly-website
    restart: unless-stopped