services:
  weld:
    build: 
      context: .
      
    ports:
      - "8501:8501"
    environment:
      - "PORT=8501"
      - "REDIS=true"
      - "DOCKER=true"
    container_name: weld-website
    restart: unless-stopped
