# This is a basic workflow to help you get started with Actions

name: Update Submodules
on:
  repository_dispatch:
    types: update
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
        default: 'main'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      # Update references
      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "deploy: ${{github.event.client_payload.module || github.event.inputs.branch}} - Auto updated submodule references" && git push || echo "No changes to commit"