# This is a basic workflow to help you get started with Actions

name: Update Submodules
on:
  repository_dispatch:
    types: update
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
        default: 'main'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Update module
        run: |
          git submodule update --remote --merge "${{github.event.client_payload.module || github.event.inputs.branch}}"
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git commit -m "deploy: ${{github.event.client_payload.module}} - ${{github.event.client_payload.sha}}"
          git push
