# This is a basic workflow to help you get started with Actions

name: Update Submodules
on:
  repository_dispatch:
    types: update
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
        default: 'main'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git clone --recurse-submodules https://github.com/${{ github.repository }} DevOps
      # Update references
      - name: Git Sumbodule Update
        env:
          BRANCH: ${{github.event.client_payload.module || github.event.inputs.branch}}
        run: |
          cd DevOps
          cd $BRANCH
          git pull
      - name: Commit update
        env:
          BRANCH: ${{github.event.client_payload.module || github.event.inputs.branch}}
        run: |
          cd DevOps
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "deploy: $BRANCH - Auto updated submodule references" && git push || echo "No changes to commit"
